name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: sudo apt install -y libgmp-dev cppcheck

    - name: make
      run: make

    - name: make check
      run: make check

    - name: run tests
      run: bash ./tests/functional_tests.sh
